<Project>
  <PropertyGroup>
    <ParentDirectoryBuildPropsPath>$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))</ParentDirectoryBuildPropsPath>
    <IsPublishable>false</IsPublishable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ImportGroup>
    <Import Project="$(ParentDirectoryBuildPropsPath)" />
  </ImportGroup>
</Project>
