# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "mikaelaolsson"
    open-pull-requests-limit: 5
    groups:
      roslynator:
        patterns:
          - "Roslynator*"
      ms-codeanalysis:
        patterns:
          - "Microsoft.CodeAnalysis*"
      umbraco:
        patterns:
          - "Umbraco*"
      xunit:
        patterns:
          - "xunit*"
      fakeiteasy:
        patterns:
          - "FakeItEasy*"

  - package-ecosystem: "npm"
    directory: "/src/Jalles.Frontend/"
    schedule:
      interval: "monthly"
    assignees:
      - "mikaelaolsson"
    open-pull-requests-limit: 5
    groups:
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
      vite:
        patterns:
          - "vite"
          - "vite-*"
      babel:
        patterns:
          - "@babel/*"
      postcss:
        patterns:
          - "postcss"
          - "postcss-*"
          - "autoprefixer"
          - "cssnano"
          - "sass"
      stylelint:
        patterns:
          - "stylelint"
          - "stylelint-*"

  - package-ecosystem: "npm"
    directory: "/src/Jalles.BackofficeExtensions/Client/"
    schedule:
      interval: "monthly"
    assignees:
      - "mikaelaolsson"
    open-pull-requests-limit: 5
    groups:
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
      tiptap:
        patterns:
          - "@tiptap/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "mikaelaolsson"

  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "wednesday"
    assignees:
      - "mikaelaolsson"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
