<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
	  <IsPackable>false</IsPackable>
	  <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	  <OutputType>Library</OutputType>
  </PropertyGroup>

	<ItemGroup>
		<Content Remove="**" />
		<Compile Remove="**" />
		<None Include="**" />
		<None Remove="node_modules/;obj/;.yarn/" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="src\styles\pages\" />
	</ItemGroup>
</Project>
