<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>netstandard2.0</TargetFramework>
	  <IsPackable>false</IsPackable>
	  <OutputType>Library</OutputType>
  </PropertyGroup>

	<ItemGroup>
		<Content Remove="**" />
		<Compile Remove="**" />
		<None Include="**" />
		<None Remove="node_modules/;obj/;.yarn/" />
	</ItemGroup>
</Project>
