
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="Our.Umbraco.Community.Contentment" />
    <PackageReference Include="Our.Umbraco.Community.Contentment.Core" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="Umbraco.Cms.Web.BackOffice" />
  </ItemGroup>

</Project>
