<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Content Remove="compilerconfig.json" />
  </ItemGroup>
  <ItemGroup>
    <None Include="compilerconfig.json" />
  </ItemGroup>

	<ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="BuildWebCompiler" Version="1.12.405" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.6.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="4.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.SqlServer" Version="7.0.9" />
    <PackageReference Include="Umbraco.Cms" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <!-- Opt-in to app-local ICU to ensure consistent globalization APIs across different platforms -->
    <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.9" />
    <PackageReference Include="Umbraco.StorageProviders.AzureBlob" Version="12.0.0" />
    <PackageReference Include="uSync" Version="12.0.2" />
    <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2.0.9" Condition="$(RuntimeIdentifier.StartsWith('linux')) or $(RuntimeIdentifier.StartsWith('win')) or ('$(RuntimeIdentifier)' == '' and !$([MSBuild]::IsOSPlatform('osx')))" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jalles.Core\Jalles.Core.csproj" />
  </ItemGroup>

	<PropertyGroup>
    <!-- Razor files are needed for the backoffice to work correctly -->
    <CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' != 'Release'">
    <!-- Remove RazorCompileOnBuild and RazorCompileOnPublish when not using ModelsMode InMemoryAuto -->
    <RazorCompileOnBuild>false</RazorCompileOnBuild>
    <RazorCompileOnPublish>false</RazorCompileOnPublish>
    <UserSecretsId>c56ea76d-02f7-4528-ba77-cdec24aa8b26</UserSecretsId>
  </PropertyGroup>

	<PropertyGroup>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	</PropertyGroup>

	<PropertyGroup>
		<CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>
	</PropertyGroup>

	<Target Name="RazorWatch" BeforeTargets="_CoreCollectWatchItems">
		<ItemGroup>
			<RazorWatch Include="**\*.cshtml" />
			<Watch Include="%(RazorWatch.FullPath)" />
		</ItemGroup>
	</Target>
</Project>
