<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="wwwroot\css\pages\**" />
    <Content Remove="wwwroot\css\pages\**" />
    <EmbeddedResource Remove="wwwroot\css\pages\**" />
    <None Remove="wwwroot\css\pages\**" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="compilerconfig.json" />
    <Content Remove="wwwroot\css\blocks\footer.scss" />
    <Content Remove="wwwroot\css\blocks\header.scss" />
    <Content Remove="wwwroot\css\blocks\main-menu.scss" />
    <Content Remove="wwwroot\css\blocks\media.scss" />
    <Content Remove="wwwroot\css\blocks\text-block.scss" />
    <Content Remove="wwwroot\css\blocks\text-blocks-collection-block.scss" />
    <Content Remove="wwwroot\css\blocks\text-contact-block.scss" />
    <Content Remove="wwwroot\css\fonts.scss" />
    <Content Remove="wwwroot\css\jalles-icons.scss" />
    <Content Remove="wwwroot\css\main.scss" />
    <Content Remove="wwwroot\css\mixins\button.scss" />
    <Content Remove="wwwroot\css\mixins\containers.scss" />
    <Content Remove="wwwroot\css\mixins\embedded-video.scss" />
    <Content Remove="wwwroot\css\mixins\icon.scss" />
    <Content Remove="wwwroot\css\mixins\links.scss" />
    <Content Remove="wwwroot\css\mixins\media.scss" />
    <Content Remove="wwwroot\css\mixins\visually-hidden.scss" />
    <Content Remove="wwwroot\css\variables.scss" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="scripts\menu-toggle.ts" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="BuildWebCompiler2022" Version="1.14.10" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.6.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="4.6.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.SqlServer" Version="7.0.9" />
    <PackageReference Include="Umbraco.Cms" Version="12.0.1" />
  </ItemGroup>

  <ItemGroup>
    <!-- Opt-in to app-local ICU to ensure consistent globalization APIs across different platforms -->
    <PackageReference Include="Microsoft.ICU.ICU4C.Runtime" Version="68.2.0.9" />
    <PackageReference Include="Umbraco.StorageProviders.AzureBlob" Version="12.0.0" />
    <PackageReference Include="uSync" Version="12.0.2" />
    <RuntimeHostConfigurationOption Include="System.Globalization.AppLocalIcu" Value="68.2.0.9" Condition="$(RuntimeIdentifier.StartsWith('linux')) or $(RuntimeIdentifier.StartsWith('win')) or ('$(RuntimeIdentifier)' == '' and !$([MSBuild]::IsOSPlatform('osx')))" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Jalles.Core\Jalles.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="compilerconfig.json" />
    <None Include="wwwroot\css\blocks\footer.scss" />
    <None Include="wwwroot\css\blocks\header.scss" />
    <None Include="wwwroot\css\blocks\main-menu.scss" />
    <None Include="wwwroot\css\blocks\media.scss" />
    <None Include="wwwroot\css\blocks\text-block.scss" />
    <None Include="wwwroot\css\blocks\text-blocks-collection-block.scss" />
    <None Include="wwwroot\css\blocks\text-contact-block.scss" />
    <None Include="wwwroot\css\fonts.scss" />
    <None Include="wwwroot\css\jalles-icons.scss" />
    <None Include="wwwroot\css\main.scss" />
    <None Include="wwwroot\css\mixins\button.scss" />
    <None Include="wwwroot\css\mixins\containers.scss" />
    <None Include="wwwroot\css\mixins\embedded-video.scss" />
    <None Include="wwwroot\css\mixins\icon.scss" />
    <None Include="wwwroot\css\mixins\links.scss" />
    <None Include="wwwroot\css\mixins\media.scss" />
    <None Include="wwwroot\css\mixins\visually-hidden.scss" />
    <None Include="wwwroot\css\variables.scss" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\build\" />
    <Folder Include="scripts\" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Razor files are needed for the backoffice to work correctly -->
    <CopyRazorGenerateFilesToPublishDirectory>true</CopyRazorGenerateFilesToPublishDirectory>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' != 'Release'">
    <!-- Remove RazorCompileOnBuild and RazorCompileOnPublish when not using ModelsMode InMemoryAuto -->
    <RazorCompileOnBuild>false</RazorCompileOnBuild>
    <RazorCompileOnPublish>false</RazorCompileOnPublish>
    <UserSecretsId>c56ea76d-02f7-4528-ba77-cdec24aa8b26</UserSecretsId>
  </PropertyGroup>

	<PropertyGroup>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	</PropertyGroup>

	<PropertyGroup>
		<CopyRefAssembliesToPublishDirectory>true</CopyRefAssembliesToPublishDirectory>
	</PropertyGroup>

	<Target Name="RazorWatch" BeforeTargets="_CoreCollectWatchItems">
		<ItemGroup>
			<RazorWatch Include="**\*.cshtml" />
			<Watch Include="%(RazorWatch.FullPath)" />
		</ItemGroup>
	</Target>
</Project>
