<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.CodeStyle" Version="4.7.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Our.Umbraco.Community.Contentment" Version="4.4.5" />
    <PackageReference Include="Our.Umbraco.Community.Contentment.Core" Version="4.4.5" />
    <PackageReference Include="Umbraco.Cms" Version="12.1.2" />
    <PackageReference Include="Umbraco.Cms.Core" Version="12.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\Content\" />
  </ItemGroup>

	<ItemGroup>
		<Compile Remove="App_Plugins\**" />
	</ItemGroup>
</Project>
