<Project>
  <PropertyGroup>
    <ParentDirectoryBuildPropsPath>$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))</ParentDirectoryBuildPropsPath>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ImportGroup>
    <Import Project="$(ParentDirectoryBuildPropsPath)" />
  </ImportGroup>

  <ItemGroup>
    <Using Include="Jalles.Core.Models.Content" Condition="'$(MSBuildProjectName)' != 'Jalles.BackofficeExtensions'" />
    <Using Include="Jalles.Core.ViewModels" Condition="'$(MSBuildProjectName)' != 'Jalles.BackofficeExtensions'" />
    <Using Include="Jalles.Core.ViewModels.Blocks" Condition="'$(MSBuildProjectName)' != 'Jalles.BackofficeExtensions'" />
    <Using Include="Jalles.Core.ViewModels.MediaTypes" Condition="'$(MSBuildProjectName)' != 'Jalles.BackofficeExtensions'" />
    <Using Include="Microsoft.AspNetCore.Mvc" />
    <Using Include="Microsoft.Extensions.Logging.Abstractions" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
    <Using Include="Umbraco.Cms.Core.Models" />
    <Using Include="Umbraco.Cms.Core.Models.PublishedContent" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Umbraco.Community.Contentment" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\BannedSymbols.txt" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(ProjectName).Tests" />
    <InternalsVisibleTo Include="Jalles.TestHelpers" />
    <!-- Needed for FakeItEasy to work with InternalsVisibleTo -->
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
