<Project>
  <PropertyGroup>
    <ParentDirectoryBuildPropsPath>$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..\'))</ParentDirectoryBuildPropsPath>
  </PropertyGroup>

  <ImportGroup>
    <Import Project="$(ParentDirectoryBuildPropsPath)" />
  </ImportGroup>

  <ItemGroup>
    <Using Include="Jalles.Core.Models.Content" />
    <Using Include="Jalles.Core.ViewModels" />
    <Using Include="Jalles.Core.ViewModels.Blocks" />
    <Using Include="Jalles.Core.ViewModels.MediaTypes" />
    <Using Include="Microsoft.AspNetCore.Mvc" />
    <Using Include="Microsoft.Extensions.Logging.Abstractions" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
    <Using Include="Umbraco.Cms.Core.Models" />
    <Using Include="Umbraco.Cms.Core.Models.PublishedContent" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Umbraco.Community.Contentment" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\BannedSymbols.txt" />
  </ItemGroup>

</Project>
